server.port=8083

authservice.whitelist=${AUTHSERVICE_WHITELIST}


authservice.url=http://authentication_service:8082
orderservice.url=http://order_service:8080
userservice.url=http://user_service:8081